/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    CountryItem: typeof import('./src/components/CountryItem.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAccordion: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UAvatarGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCommandPalette: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_@babel+parser@7.26.3_embla-carousel@8.5.1_radix-vue@1.9.11_vue@3.5.13_ee23vaoi2uq3jvjrmah6qfmije/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  }
}
